Clientbackup script
VeritasOS/netbackup-api-code-samples pull request #81
Opened 2020-09-15 13:16 UTC by tcsimerson

ClientBackup.ps1 is a PowerShell script designed to backup a Windows client using a command line specified policy name and API key.
[ClientBackup.zip](https://github.com/VeritasOS/netbackup-api-code-samples/files/5225088/ClientBackup.zip)

2020-09-21 16:16 UTC, rkennedy requested changes

2020-09-21 16:16 UTC, rkennedy commented on README.md
> -### NetBackup API Code Samples
Please don't delete the top-level readme.

2020-09-21 16:16 UTC, rkennedy commented on recipes/powershell/ClientBackup.ps1
> +    [string]$p = $(throw "Please speicfy the policy name using -p parameter."),
```suggestion
    [string]$p = $(throw "Please specify the policy name using -p parameter."),
```

2020-10-07 17:11 UTC, tcsimerson commented
Rob,

Sorry about this.  I’m a GitHub noob.  Not sure how to fix this.  Suggestions?

Tom C. Simerson
Account SE and Data Protection TC
Veritas Technologies LLC

Mobile: (972) 750 6519
tom.simerson@veritas.com<mailto:tom.simerson@veritas.com>

[cid:image001.png@01D69CA3.00F951B0]
Simplifying Complexity

This message (including any attachments) is intended only for the use of the individual or entity to which it is addressed and may contain information that is non-public, proprietary, privileged, confidential, and exempt from disclosure under applicable law or may constitute as attorney work product. If you are not the intended recipient, you are hereby notified that any use, dissemination, distribution, or copying of this communication is strictly prohibited. If you have received this communication in error, notify us immediately by telephone and (i) destroy this message if a facsimile or (ii) delete this message immediately if this is an electronic communication.


From: Rob Kennedy <notifications@github.com>
Sent: Monday, September 21, 2020 11:17 AM
To: VeritasOS/netbackup-api-code-samples <netbackup-api-code-samples@noreply.github.com>
Cc: Tom Simerson <Tom.Simerson@veritas.com>; Author <author@noreply.github.com>
Subject: [Newsletter][EXTERNAL] Re: [VeritasOS/netbackup-api-code-samples] Clientbackup script (#81)


@rkennedy requested changes on this pull request.

________________________________

In README.md<https://github.com/VeritasOS/netbackup-api-code-samples/pull/81#discussion_r490547557>:

> @@ -1,56 +0,0 @@



-### NetBackup API Code Samples



Please don't delete the top-level readme.

________________________________

In recipes/powershell/ClientBackup.ps1<https://github.com/VeritasOS/netbackup-api-code-samples/pull/81#discussion_r490548009>:

> +        * one incremental



+    * Client name added to Clients tab



+* Use command line parameters to specify the following parameters



+    * -policy (to reference above policy)



+    * -apikey (generated through NetBackup web UI)



+* API key uesr must have following privileges assigned to it's role:



+    * Minimum specific privileges:



+        * Global -> NetBackup management -> NetBackup images -> View



+        * Global -> Protection -> Policies -> View



+        * Global -> Protection -> Policies -> Manual Backup



+* PowerShell Execution Policy needs to be opened



+#>



+



+



+param (



+    [string]$p = $(throw "Please speicfy the policy name using -p parameter."),


⬇️ Suggested change

-    [string]$p = $(throw "Please speicfy the policy name using -p parameter."),



+    [string]$p = $(throw "Please specify the policy name using -p parameter."),



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/VeritasOS/netbackup-api-code-samples/pull/81#pullrequestreview-490970230>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQTXLL4ZLG3P4JCXT5Y2VBLSG537ZANCNFSM4RND25HQ>.

2020-10-08 03:13 UTC, rkennedy commented
If you don't already have a directory with your work in it, then clone this repo and check out this branch. (You might already have something, since it's what you used to submit this in the first place.) Then, make the changes I've requested:

1. To restore the deleted readme, I think it's sufficient to run `git checkout origin/master README.md`. When you run `git status`, that file should appear as staged (in green).
2. Fix the spelling, and use `git add` to stage the fixed file, too.

Run `git commit` and describe the changes, and finally run `git push` to send them to GitHub. This pull request should get updated automatically, and I'll get a notification.

If you hit any problems, you can find me on Teams, and I can help out or take over any time.

2020-10-26 01:59 UTC, rkennedy approved these changes

2020-10-26 02:04 UTC, merged